server.port: 8082

spring:
  application.name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:8761/eureka